before_install:
      sudo pip install awscli      
script: 
      #aws s3 cp . s3://online-calc.xyz/ --recursive --exclude "*.git/*" --exclude "*.md" --exclude ".travis.yml" --include "*.js" --include "*.css" --include "*.html" --endpoint-url  "http://online-calc.xyz.s3-website-us-east-1.amazonaws.com"
      aws s3 sync . s3://online-calc.xyz --exclude "*.git/*" --exclude "*.md" --exclude ".travis.yml"
deploy:
      provider: s3
      access_key_id: "$access_key_id"
      secret_access_key: "$secret_access_key"
      bucket: "online-calc.xyz"
